///////////////////////////////////////////////////////////
//  Familia.cs
//  Implementation of the Class Familia
//  Generated by Enterprise Architect
//  Created on:      22-may-2025 21:16:24
//  Original author: gasto
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace Services.DomainModel
{
	/// <summary>
	/// This class (a) defines behaviour for components having children, (b) stores
	/// child components, and (c) implements child-related operations in the Component
	/// interface.
	/// </summary>
	/// 

	
	public class Familia : Component {

		private List<Component> hijos = new List<Component>();

        public string Nombre { get; set; }

        public Familia(){

		}


		/// 
		/// <param name="component"></param>
		public override void Add(Component component){

			hijos.Add(component);
		}

		/// 
		/// <param name="component"></param>
		public override void Remove(Component component){
			component.Remove(component);
		}

	}//end Familia

}//end namespace Patrones