///////////////////////////////////////////////////////////
//  Patente.cs
//  Implementation of the Class Patente
//  Generated by Enterprise Architect
//  Created on:      22-may-2025 21:16:23
//  Original author: gasto
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using Patrones;
namespace Patrones {
	/// <summary>
	/// This class (a) represents leaf objects in the composition, and (b) defines
	/// behaviour for primitive objects in the composition.
	/// </summary>
	public class Patente : Component {

		public Patente(){

		}


		/// 
		/// <param name="component"></param>
		public override void Add(Component component){
			throw new Exception("No se pueden agregar elementos en un hijo tipo hoja");
		}

		/// 
		/// <param name="component"></param>
		public override void Remove(Component component){
            throw new Exception("No se pueden eliminar elementos en un hijo tipo hoja");
        }

    }//end Patente

}//end namespace Patrones